### ISSUE TITLE
Incorrect code generation for '&&' and '||' operators

### ISSUE THREAD

**Issue by Jenny-fa** [asutton/beaker#6]
@asutton @thehexia: The current implementation of the code generation routines for the `&&` and `||` operators in beaker/generator.cpp use the `llvm::IRBuilder::CreateAnd()` and `llvm::IRBuilder::CreateOr()` member functions, which produce instructions for the _bitwise_ AND and OR operations, respectively—not the logical AND and OR (as I assume was the intention).

From llvm/IR/IRBuilder.h:
```cpp
  Value *CreateAnd(Value *LHS, Value *RHS, const Twine &Name = "") {
    if (Constant *RC = dyn_cast<Constant>(RHS)) {
      if (isa<ConstantInt>(RC) && cast<ConstantInt>(RC)->isAllOnesValue())
        return LHS;  // LHS & -1 -> LHS
      if (Constant *LC = dyn_cast<Constant>(LHS))
        return Insert(Folder.CreateAnd(LC, RC), Name);
    }
    return Insert(BinaryOperator::CreateAnd(LHS, RHS), Name);
  }

  Value *CreateOr(Value *LHS, Value *RHS, const Twine &Name = "") {
    if (Constant *RC = dyn_cast<Constant>(RHS)) {
      if (RC->isNullValue())
        return LHS;  // LHS | 0 -> LHS
      if (Constant *LC = dyn_cast<Constant>(LHS))
        return Insert(Folder.CreateOr(LC, RC), Name);
    }
    return Insert(BinaryOperator::CreateOr(LHS, RHS), Name);
  }
```

FYI, I verified this myself using a test program—`llvm::IRBuilder::CreateAnd()` and `llvm::IRBuilder::CreateOr()` produce the '[and](http://llvm.org/releases/3.6.0/docs/LangRef.html#and-instruction)' and '[or](http://llvm.org/releases/3.6.0/docs/LangRef.html#or-instruction)' instructions, respectively.

**Comment by asutton** [comment]
Submit a patch?


Andrew Sutton

**Comment by Jenny-fa** [comment]
See pull request #7.
